#@@CopyFile@@
import os

import csharp.csharp

from SCons.Environment import Environment
import SCons.Util

env = Environment()

csharp.csharp.generate(env)
env["CSCFLAGS"] = SCons.Util.CLVar("-nologo")

Src = ['Src/CSharpExample.cs', 'Src/StateMachine.cs', 'Src/StateMachineTables.cs']

env.CLIProgram(target='StateMachine', source=Src)
