#@@CopyFile@@
import os

from SCons.Environment import Environment

env = Environment()

Src = ['Src/CPPExample.cpp', 'Src/SMExceptions.cpp', 'Src/StateMachine.cpp']
CPPFlags = ''
if os.name == 'nt':
  Src.append('Src/WinIOFile.cpp')
  env.Append(CCFLAGS=['/std:c++17', '/EHsc'])
else:
  Src.append('Src/PosixIOFile.cpp')

env.Program(target='StateMachine', source=Src)
